language: python
python:
    - "2.7"

os:
    - linux

#services:  # No need for rabbit with broken integration tests
#    - rabbitmq

install:
    - python setup.py develop
    - python setup.py test

script:
    - nosetests -v
