language: python
python:
    - "2.7"

os:
    - linux

#services:  # No need for rabbit with broken integration tests
#    - rabbitmq

install:
    - travis_retry pip install tox==1.8

script:
    - tox

after_script:
    - tox -e py27-coveralls
