language: python
python:
    #    - "2.6" #unittest.skip N/A in py2.6
    - "2.7"

os:
    - linux

services:
    - rabbitmq

install:
    - python setup.py develop
    - python setup.py test

script:
    - nosetests -v

matrix:
    fast_finish: true
