language: python
python:
    - "2.7"

os:
    - linux

services:
    - rabbitmq

install:
    - travis_retry pip install tox==1.8

env:
    global:
          # AWS credentials for rail/build-funsize
        - secure: "NJl0jbStascebyB/shlxMKMyywvMC2LniiKjdoVwjYakqfVWMiVc9y/Y4bPSYq1mLHbfNnGVHbqfi8P2o+4pcg0iXGcQC0E+VNGF1U+gn2lBkvPbxksVRHBCyOIfnASTxqyShuyJohvS/X8bQjzVyoKUJZZPmBLzysjwX7WgpFE="
        - secure: "Uvs9NwwYi+p/xoosirEM7un4BtS6/mWDY/zPyq/kZmzfwEOpRno0MqJcwtOthxNw12z6efIkzi+XsCOEt3ULZchkcaYKaOGI6fFpqhVKlCHdzw9Ia6uTeg1XzsFkvLJkuUGpSsSTFBZv37Ik8dd5FTeirv8qn2VIDfJGb9deJEU="
          # AWS credentials for mozilla/build-funsize to make travis work for both repos
        - secure: "pZBYgOlxqzIgf62aGJuHXWhwqWYfLYhZA53mezv1wvbrnRRG5vBTBrafum7pGaHDs9+TROFGILV3ig25DrnO5schau4ILy0zXQ/VGyVXdEBW5sTardSoJAPo+81gxHXdAuEMLE9eGbKW87+7JFI9QcuVodCquiHJUrGfb4txAOU="
        - secure: "h/kK5FbzNENdYI15hIbFh6Ha2uwpUQFID8ajzhpFa4XqTdQT+Lut5gQSjBHMl3IPB11LNCUpmosC4n4r79kYKgfjjYpghQck8VrUepWqB/JtiY6oylxyShJbfwCdf0fxjEvh76qnreNHV8STBph1qJ4DgWz1c8/BBd6tHuc/840="
    matrix:
        - FUNSIZE_LOCAL_CACHE_DIR=/tmp/funnycache
        - FUNSIZE_S3_UPLOAD_BUCKET=mozilla-releng-funsize-travis

script:
    - tox -e py27,py27-travis

after_script:
    - tox -e py27-coveralls
